//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeProManager {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeProManager.strings", typeof(locStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this app.
        /// </summary>
        internal static string aboutThisApp {
            get {
                return ResourceManager.GetString("aboutThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add task.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add topic.
        /// </summary>
        internal static string AddTopic {
            get {
                return ResourceManager.GetString("AddTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application in :.
        /// </summary>
        internal static string appInLanguage {
            get {
                return ResourceManager.GetString("appInLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the task ?.
        /// </summary>
        internal static string areYouSureDeleteTheTask {
            get {
                return ResourceManager.GetString("areYouSureDeleteTheTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birthday calendar.
        /// </summary>
        internal static string BirthdayCalendar {
            get {
                return ResourceManager.GetString("BirthdayCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue.
        /// </summary>
        internal static string BlueTheme {
            get {
                return ResourceManager.GetString("BlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birthday.
        /// </summary>
        internal static string chkBirthdayText {
            get {
                return ResourceManager.GetString("chkBirthdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à descriptions.
        /// </summary>
        internal static string chkDescriptionsText {
            get {
                return ResourceManager.GetString("chkDescriptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Important.
        /// </summary>
        internal static string chkImportantText {
            get {
                return ResourceManager.GetString("chkImportantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeatable.
        /// </summary>
        internal static string chkRepeatableText {
            get {
                return ResourceManager.GetString("chkRepeatableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch application at Windows startup.
        /// </summary>
        internal static string chkRunAtWindowsStartupText {
            get {
                return ResourceManager.GetString("chkRunAtWindowsStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à topics.
        /// </summary>
        internal static string chkTopicsText {
            get {
                return ResourceManager.GetString("chkTopicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calendar background.
        /// </summary>
        internal static string ColorOfBirthdayCalendarBackground {
            get {
                return ResourceManager.GetString("ColorOfBirthdayCalendarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Primary squares.
        /// </summary>
        internal static string ColorOfBirthdayCalendarSquaresPrimary {
            get {
                return ResourceManager.GetString("ColorOfBirthdayCalendarSquaresPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secondary squares.
        /// </summary>
        internal static string ColorOfBirthdayCalendarSquaresSecondary {
            get {
                return ResourceManager.GetString("ColorOfBirthdayCalendarSquaresSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tertiary squares.
        /// </summary>
        internal static string ColorOfBirthdayCalendarSquaresTertiary {
            get {
                return ResourceManager.GetString("ColorOfBirthdayCalendarSquaresTertiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calendar text.
        /// </summary>
        internal static string ColorOfBirthdayCalendarText {
            get {
                return ResourceManager.GetString("ColorOfBirthdayCalendarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input fields background.
        /// </summary>
        internal static string ColorOfInputFieldsBackground {
            get {
                return ResourceManager.GetString("ColorOfInputFieldsBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input fields text.
        /// </summary>
        internal static string ColorOfInputFieldsText {
            get {
                return ResourceManager.GetString("ColorOfInputFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main window background.
        /// </summary>
        internal static string ColorOfMainWindowBackground {
            get {
                return ResourceManager.GetString("ColorOfMainWindowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panels and tasks borders.
        /// </summary>
        internal static string ColorOfPanelsAndTasksBorders {
            get {
                return ResourceManager.GetString("ColorOfPanelsAndTasksBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task description text.
        /// </summary>
        internal static string ColorOfPnlTaskDescription {
            get {
                return ResourceManager.GetString("ColorOfPnlTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task description background.
        /// </summary>
        internal static string ColorOfPnlTaskDescriptionBackground {
            get {
                return ResourceManager.GetString("ColorOfPnlTaskDescriptionBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right panel background.
        /// </summary>
        internal static string ColorOfRightPanelBackground {
            get {
                return ResourceManager.GetString("ColorOfRightPanelBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secondary windows background.
        /// </summary>
        internal static string ColorOfSecondaryWindowsBackground {
            get {
                return ResourceManager.GetString("ColorOfSecondaryWindowsBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task titles text.
        /// </summary>
        internal static string ColorOfTaskTitles {
            get {
                return ResourceManager.GetString("ColorOfTaskTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task titles background.
        /// </summary>
        internal static string ColorOfTaskTitlesBackground {
            get {
                return ResourceManager.GetString("ColorOfTaskTitlesBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate and cancel buttons.
        /// </summary>
        internal static string ColorOfValidateButton {
            get {
                return ResourceManager.GetString("ColorOfValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm copy.
        /// </summary>
        internal static string confirmCopy {
            get {
                return ResourceManager.GetString("confirmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm deletion.
        /// </summary>
        internal static string confirmDeletion {
            get {
                return ResourceManager.GetString("confirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customize application colors.
        /// </summary>
        internal static string CustomizeAppColors {
            get {
                return ResourceManager.GetString("CustomizeAppColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database has been corrupted and will be rebuilt..
        /// </summary>
        internal static string databaseCorrupted {
            get {
                return ResourceManager.GetString("databaseCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database file could not be found in the application directory. A blank file will be created..
        /// </summary>
        internal static string databaseNotFound {
            get {
                return ResourceManager.GetString("databaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day after tomorrow.
        /// </summary>
        internal static string dayAfterTomorrow {
            get {
                return ResourceManager.GetString("dayAfterTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while deleting all topics..
        /// </summary>
        internal static string deleteAllTopicsError {
            get {
                return ResourceManager.GetString("deleteAllTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All topics and tasks have been deleted..
        /// </summary>
        internal static string deleteAllTopicsSuccess {
            get {
                return ResourceManager.GetString("deleteAllTopicsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete all topics.
        /// </summary>
        internal static string deleteAllTopicsTitle {
            get {
                return ResourceManager.GetString("deleteAllTopicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to delete all topics and all associated tasks?.
        /// </summary>
        internal static string deleteAllTopicsWarning {
            get {
                return ResourceManager.GetString("deleteAllTopicsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting topic will also result in the removal of related tasks..
        /// </summary>
        internal static string delTopicWillRemoveRelTasks {
            get {
                return ResourceManager.GetString("delTopicWillRemoveRelTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display by topic.
        /// </summary>
        internal static string displayByTopic {
            get {
                return ResourceManager.GetString("displayByTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In addition to due dates export:.
        /// </summary>
        internal static string exportDeadlineAndTitle {
            get {
                return ResourceManager.GetString("exportDeadlineAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web pages|*.html; *.htm.
        /// </summary>
        internal static string exportHtmlFilter {
            get {
                return ResourceManager.GetString("exportHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export all data to a web page.
        /// </summary>
        internal static string exportHtmlTitle {
            get {
                return ResourceManager.GetString("exportHtmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while exporting SQL: {0}.
        /// </summary>
        internal static string exportSqlError {
            get {
                return ResourceManager.GetString("exportSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL file (*.sql)|*.sql.
        /// </summary>
        internal static string exportSqlFilter {
            get {
                return ResourceManager.GetString("exportSqlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export completed successfully..
        /// </summary>
        internal static string exportSqlSuccess {
            get {
                return ResourceManager.GetString("exportSqlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export all data.
        /// </summary>
        internal static string exportSqlTitle {
            get {
                return ResourceManager.GetString("exportSqlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while executing the SQL script..
        /// </summary>
        internal static string importSqlError {
            get {
                return ResourceManager.GetString("importSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL script (*.sql)|*.sql.
        /// </summary>
        internal static string importSqlFilter {
            get {
                return ResourceManager.GetString("importSqlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data successfully inserted into the database..
        /// </summary>
        internal static string importSqlSuccess {
            get {
                return ResourceManager.GetString("importSqlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert data from a SQL script.
        /// </summary>
        internal static string importSqlTitle {
            get {
                return ResourceManager.GetString("importSqlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string langFrench {
            get {
                return ResourceManager.GetString("langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spanish.
        /// </summary>
        internal static string langSpanish {
            get {
                return ResourceManager.GetString("langSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à April.
        /// </summary>
        internal static string lblAprilText {
            get {
                return ResourceManager.GetString("lblAprilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à August.
        /// </summary>
        internal static string lblAugustText {
            get {
                return ResourceManager.GetString("lblAugustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deadline.
        /// </summary>
        internal static string lblDeadlineText {
            get {
                return ResourceManager.GetString("lblDeadlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à December.
        /// </summary>
        internal static string lblDecemberText {
            get {
                return ResourceManager.GetString("lblDecemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string lblDescriptionText {
            get {
                return ResourceManager.GetString("lblDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à February.
        /// </summary>
        internal static string lblFebruaryText {
            get {
                return ResourceManager.GetString("lblFebruaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à January.
        /// </summary>
        internal static string lblJanuaryText {
            get {
                return ResourceManager.GetString("lblJanuaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à July.
        /// </summary>
        internal static string lblJulyText {
            get {
                return ResourceManager.GetString("lblJulyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à June.
        /// </summary>
        internal static string lblJuneText {
            get {
                return ResourceManager.GetString("lblJuneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uses portions of code and UI elements by David Rossy.
        ///Pre‑1.0 versions tested by Julien Terrapon.
        ///
        ///This product was originally developed in an educational context,
        ///as part of learning object‑oriented programming.
        ///It is free software and provided as is.
        ///
        ///
        ///Version 1.8.3 - June 2026
        ///Developed by Laurent Barraud..
        /// </summary>
        internal static string lblLicenceText {
            get {
                return ResourceManager.GetString("lblLicenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à March.
        /// </summary>
        internal static string lblMarchText {
            get {
                return ResourceManager.GetString("lblMarchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à May.
        /// </summary>
        internal static string lblMayText {
            get {
                return ResourceManager.GetString("lblMayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à November.
        /// </summary>
        internal static string lblNovemberText {
            get {
                return ResourceManager.GetString("lblNovemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à October.
        /// </summary>
        internal static string lblOctoberText {
            get {
                return ResourceManager.GetString("lblOctoberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority.
        /// </summary>
        internal static string lblPriorityText {
            get {
                return ResourceManager.GetString("lblPriorityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à September.
        /// </summary>
        internal static string lblSeptemberText {
            get {
                return ResourceManager.GetString("lblSeptemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        internal static string lblTitleText {
            get {
                return ResourceManager.GetString("lblTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Topic.
        /// </summary>
        internal static string lblTopicText {
            get {
                return ResourceManager.GetString("lblTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Year.
        /// </summary>
        internal static string lblYearText {
            get {
                return ResourceManager.GetString("lblYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customize application colors.
        /// </summary>
        internal static string lnkChangeAppColorsText {
            get {
                return ResourceManager.GetString("lnkChangeAppColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export all tasks to a SQL script.
        /// </summary>
        internal static string lnkExportTasksToSqlText {
            get {
                return ResourceManager.GetString("lnkExportTasksToSqlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert tasks from a SQL script.
        /// </summary>
        internal static string lnkInsertTasksFromSqlText {
            get {
                return ResourceManager.GetString("lnkInsertTasksFromSqlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next days.
        /// </summary>
        internal static string nextDays {
            get {
                return ResourceManager.GetString("nextDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No results found..
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reassign.
        /// </summary>
        internal static string ReassignTask {
            get {
                return ResourceManager.GetString("ReassignTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeat this task for another day?.
        /// </summary>
        internal static string repeatTaskAnotherDay {
            get {
                return ResourceManager.GetString("repeatTaskAnotherDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search crashed. No results available..
        /// </summary>
        internal static string SearchCrashedNoResults {
            get {
                return ResourceManager.GetString("SearchCrashedNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a preset theme.
        /// </summary>
        internal static string SelectPreSetTheme {
            get {
                return ResourceManager.GetString("SelectPreSetTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dates.
        /// </summary>
        internal static string tabDatesText {
            get {
                return ResourceManager.GetString("tabDatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finished.
        /// </summary>
        internal static string tabFinishedText {
            get {
                return ResourceManager.GetString("tabFinishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string tabSettingsText {
            get {
                return ResourceManager.GetString("tabSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Topics.
        /// </summary>
        internal static string tabTopicsText {
            get {
                return ResourceManager.GetString("tabTopicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task description.
        /// </summary>
        internal static string taskDescription {
            get {
                return ResourceManager.GetString("taskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task description font size:
        ///.
        /// </summary>
        internal static string taskDescriptionFontSizeText {
            get {
                return ResourceManager.GetString("taskDescriptionFontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Today.
        /// </summary>
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tomorrow.
        /// </summary>
        internal static string tomorrow {
            get {
                return ResourceManager.GetString("tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Topic.
        /// </summary>
        internal static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total tasks to be completed:.
        /// </summary>
        internal static string totalTasksToComplete {
            get {
                return ResourceManager.GetString("totalTasksToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two days ago.
        /// </summary>
        internal static string twoDaysAgo {
            get {
                return ResourceManager.GetString("twoDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New topic.
        /// </summary>
        internal static string txtTopicText {
            get {
                return ResourceManager.GetString("txtTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        internal static string ValidateTask {
            get {
                return ResourceManager.GetString("ValidateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yesterday.
        /// </summary>
        internal static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please provide a name for the new topic..
        /// </summary>
        internal static string youMustFillInANameForYourNewTopic {
            get {
                return ResourceManager.GetString("youMustFillInANameForYourNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must give a title to your task.
        /// </summary>
        internal static string youMustGiveATitleToYourTask {
            get {
                return ResourceManager.GetString("youMustGiveATitleToYourTask", resourceCulture);
            }
        }
    }
}
