//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeProManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string appLanguageCode {
            get {
                return ((string)(this["appLanguageCode"]));
            }
            set {
                this["appLanguageCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int exportMode {
            get {
                return ((int)(this["exportMode"]));
            }
            set {
                this["exportMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int taskDescriptionFontSize {
            get {
                return ((int)(this["taskDescriptionFontSize"]));
            }
            set {
                this["taskDescriptionFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F5F7FA")]
        public string colorOfMainWindowBackground {
            get {
                return ((string)(this["colorOfMainWindowBackground"]));
            }
            set {
                this["colorOfMainWindowBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F5F7FA")]
        public string colorOfRightPanelBackground {
            get {
                return ((string)(this["colorOfRightPanelBackground"]));
            }
            set {
                this["colorOfRightPanelBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E6EBEF")]
        public string colorOfSecondaryWindowsBackground {
            get {
                return ((string)(this["colorOfSecondaryWindowsBackground"]));
            }
            set {
                this["colorOfSecondaryWindowsBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string colorOfPanelsBackground {
            get {
                return ((string)(this["colorOfPanelsBackground"]));
            }
            set {
                this["colorOfPanelsBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string colorOfInputFieldsBackground {
            get {
                return ((string)(this["colorOfInputFieldsBackground"]));
            }
            set {
                this["colorOfInputFieldsBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#B6C0C1")]
        public string colorOfValidateButton {
            get {
                return ((string)(this["colorOfValidateButton"]));
            }
            set {
                this["colorOfValidateButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#355A62")]
        public string colorOfBirthdayCalendarText {
            get {
                return ((string)(this["colorOfBirthdayCalendarText"]));
            }
            set {
                this["colorOfBirthdayCalendarText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E4F3ED")]
        public string colorOfBirthdayCalendarSquaresPrimary {
            get {
                return ((string)(this["colorOfBirthdayCalendarSquaresPrimary"]));
            }
            set {
                this["colorOfBirthdayCalendarSquaresPrimary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F1F3F8")]
        public string colorOfBirthdayCalendarSquaresSecondary {
            get {
                return ((string)(this["colorOfBirthdayCalendarSquaresSecondary"]));
            }
            set {
                this["colorOfBirthdayCalendarSquaresSecondary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FBFCE9")]
        public string colorOfBirthdayCalendarSquaresTertiary {
            get {
                return ((string)(this["colorOfBirthdayCalendarSquaresTertiary"]));
            }
            set {
                this["colorOfBirthdayCalendarSquaresTertiary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F5F7FA")]
        public string colorOfBirthdayCalendarBackground {
            get {
                return ((string)(this["colorOfBirthdayCalendarBackground"]));
            }
            set {
                this["colorOfBirthdayCalendarBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string colorOfLblTaskDescriptionBackground {
            get {
                return ((string)(this["colorOfLblTaskDescriptionBackground"]));
            }
            set {
                this["colorOfLblTaskDescriptionBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string colorOfLblTaskDescriptionText {
            get {
                return ((string)(this["colorOfLblTaskDescriptionText"]));
            }
            set {
                this["colorOfLblTaskDescriptionText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string colorOfTaskTitlesText {
            get {
                return ((string)(this["colorOfTaskTitlesText"]));
            }
            set {
                this["colorOfTaskTitlesText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string colorOfInputFieldsText {
            get {
                return ((string)(this["colorOfInputFieldsText"]));
            }
            set {
                this["colorOfInputFieldsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedThemeIndex {
            get {
                return ((int)(this["selectedThemeIndex"]));
            }
            set {
                this["selectedThemeIndex"] = value;
            }
        }
    }
}
